#1번
CREATE TABLE BOOK_INFO(
	BOOK_NUM INT PRIMARY KEY #도서 번호
	,BOOK_NAME VARCHAR(20) #도서명
	,BOOK_WRITER VARCHAR(20) NOT NULL #저자
	,BOOK_PRICE INT #도서 가격
	,BOOK_WRITE VARCHAR(20) #출판사
	,BOOK_DATE DATETIME DEFAULT SYSDATE() #발행일
);

#2번
INSERT INTO BOOK_INFO(
BOOK_NUM
, BOOK_NAME
, BOOK_WRITER
, BOOK_PRICE
, BOOK_WRITE
, BOOK_DATE
) 
VALUES(
101, '자바 기초', '홍길동', 30000, 'A출판', '2025-02-15'
);

INSERT INTO BOOK_INFO(
BOOK_NUM
, BOOK_NAME
, BOOK_WRITER
, BOOK_PRICE
, BOOK_WRITE
, BOOK_DATE
) 
VALUES(
102, '리엑트 기초', '이순신', 20000, 'B출판', '2025-01-22'
);

#3번
UPDATE BOOK_INFO
SET BOOK_NAME = '자바_고급'
, BOOK_PRICE = 25000
, BOOK_WRITE = 'IT출판'
WHERE BOOK_NUM = 101;

#4번
SELECT EMPNO, ENAME, SAL, COMM AS '인센티브'
FROM emp
WHERE SAL BETWEEN 500 AND 3000 AND COMM IS NULL;

#5번
SELECT EMPNO, ENAME, JOB, HIREDATE
FROM emp
WHERE ENAME LIKE '%병%' OR ENAME LIKE '%김%'
ORDER BY JOB ASC ,EMPNO DESC;

#6번
SELECT EMPNO, ENAME, DEPTNO,
 CASE  
 WHEN DEPTNO = 10 THEN '인사부' 
	WHEN DEPTNO = 20 THEN '영업부' 
	WHEN DEPTNO = 30 THEN '개발부' 
	ELSE '생산부'
	END AS '부서명'
FROM emp;

#7번
SELECT EMPNO, ENAME, HIREDATE, IFNULL(COMM,0)
FROM emp
WHERE TO_CHAR(HIREDATE,'MM') % 2 = 0
ORDER BY HIREDATE ASC;

#8번
SELECT EMPNO, ENAME, HIREDATE, SAL, E.DEPTNO, D.DEPTNO, DNAME
FROM emp E INNER JOIN dept D
ON E.DEPTNO = d.DEPTNO
WHERE DNAME != '인사부' AND SAL >= 500
ORDER BY EMPNO DESC, ENAME ASC;

#9번
SELECT EMPNO, E.DEPTNO, D.DEPTNO, DNAME, ENAME AS '이름'
FROM emp E INNER JOIN dept D
ON E.DEPTNO = d.DEPTNO;
WHERE HIREDATE BETWEEN'2003' AND '2007' AND ENAME LIKE '_';












