
-- 연습용 자동차 정보 테이블
CREATE TABLE TEST_CAR(
	MODEL_NUMBER INT PRIMARY KEY -- 중복 데이터X, NULL X
	, MODEL_NAME VARCHAR(20) NOT NULL
	, PRICE INT
	, BRAND VARCHAR(20)
);

SELECT * FROM test_car;

-- 게시글 정보
CREATE TABLE BOARD(
	BOARD_NUM INT PRIMARY KEY
	, TITLE VARCHAR(30) NOT NULL
	, WRITER VARCHAR(20)
	, READ_CNT INT DEFAULT 0
);

SELECT * FROM board;

COMMIT;
ROLLBACK;

-- 데이터 삽입
-- INSERT INTO 테이블명 (컬럼, 컬럼) VALUES (데이터, 데이터...);
INSERT INTO board (BOARD_NUM, TITLE, WRITER, READ_CNT) 
VALUES (1, '제목1', '김자바', 0);

INSERT INTO board (BOARD_NUM, TITLE, WRITER, READ_CNT) 
VALUES (2, '제목1', '김자바', 0);

INSERT INTO board (BOARD_NUM, TITLE, READ_CNT) 
VALUES (3, '제목2', 3);

INSERT INTO board (BOARD_NUM, READ_CNT) 
VALUES (4, 3);

INSERT INTO board (BOARD_NUM, TITLE) 
VALUES (5, '제목3');

INSERT INTO board VALUES(11, '제목5', '김', 10);

SELECT * FROM board;

ROLLBACK;
COMMIT;




