
#상품정보 테이블
CREATE TABLE ITEM_INFO (
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE
	, ITEM_PRICE INT NOitem_infoT NULL
	, SELLER VARCHAR(10)
	, ITEM_INTRO VARCHAR(20)
	, REG_DATE DATETIME DEFAULT SYSDATE()
);

INSERT INTO item_info VALUES(1, '상품1', 45000, '이자바', '상품1 입니다', NOW());
COMMIT;
SELECT * FROM item_info;
#주문정보 테이블
CREATE TABLE ORDER_INFO(
	ORDER_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_NUM INT NOT NULL REFERENCES ITEM_INFO (ITEM_NUM)
	, BUYER VARCHAR(20) NOT NULL
	, BUY_CNT INT NOT NULL
	, BUY_PRICE INT NOT NULL
	, BUY_DATE DATETIME DEFAULT SYSDATE() 
);

SELECT * FROM order_info;

SELECT ITEM_NAME, ITEM_PRICE, BUY_CNT, BUY_PRICE, BUYER, BUY_DATE
FROM item_info INNER JOIN order_info
ON ITEM_INFO.ITEM_NUM = order_info.ITEM_NUM;

SELECT * FROM emp;
DESC emp;
SELECT * FROM dept;
DESC dept;
#사원명 모든 사원의 사번, 사원명, 급여, 부서번호, 부서명
SELECT EMPNO, ENAME, SAL, EMP.DEPTNO, DNAME, LOC
FROM emp INNER JOIN dept
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM board;
DESC board;
SELECT * FROM board_reply;
DESC board_reply;

#BOARD_REPLY 테이블의 컬럼 변경
ALTER TABLE board_reply CHANGE COLUMN CONTENT REPLY_CONTENT VARCHAR(20);
ALTER TABLE board_reply CHANGE COLUMN WRITER REPLY_WRITER VARCHAR(20);
ALTER TABLE board_reply CHANGE COLUMN REG_DATE REPLY_REG_DATE DATETIME DEFAULT SYSDATE();

#모든 게시글의 게시글번호, 제목, 작성자 및 게시글에 달린 댓글 내용, 댓글 작성자를 조회
SELECT BOARD.BOARD_NUM, TITLE, WRITER, REPLY_CONTENT, REPLY_WRITER
FROM board INNER JOIN board_reply
ON BOARD.BOARD_NUM = board_reply.BOARD_NUM;


