SELECT * FROM study_student;
-- 1.
SELECT STU_NUM AS '학생번호', STU_NAME AS '학생명', KOR_SCORE, ENG_SCORE 
FROM study_student 
WHERE KOR_SCORE >= 60 AND ENG_SCORE >= 70;
-- 2.
SELECT * 
FROM study_student 
WHERE (CLASS_NAME = '디자인반' OR CLASS_NAME = '영상반') 
AND HOBBY IS NOT NULL;
-- 3.
SELECT STU_NUM, STU_NAME, KOR_SCORE 
FROM study_student 
WHERE KOR_SCORE BETWEEN 70 AND 85
AND STU_NAME LIKE '김%' 
ORDER BY STU_NUM DESC;
-- 4.
SELECT STU_NUM, STU_NAME, CLASS_NAME, ENG_SCORE
FROM study_student 
WHERE HOBBY IS NOT NULL 
ORDER BY CLASS_NAME ASC, ENG_SCORE DESC;
-- 5.
SELECT * 
FROM study_student 
WHERE KOR_SCORE + ENG_SCORE >= 170;
-- 6.
SELECT STU_NUM, STU_NAME, KOR_SCORE, ENG_SCORE, KOR_SCORE + ENG_SCORE AS 총점
FROM study_student
WHERE CLASS_NAME != '영상반';
-- NOT IN ('영상반')
-- 7.
SELECT DISTINCT HOBBY 
FROM study_student
WHERE HOBBY IS NOT NULL;








