#1.
CREATE TABLE MY_MEMBER(
	MEMBER_NUMBER INT PRIMARY KEY
	, MEMBER_ID VARCHAR(20) NOT NULL
	, MEMBER_PASSWARD VARCHAR(40) NOT NULL
	, MEMBER_NAME VARCHAR(20)
	, MEMBER_AGE INT DEFAULT 0
	, MEMBER_EMAIL VARCHAR(30)
	);
	
#2.
INSERT INTO MY_MEMBER(MEMBER_NUMBER, MEMBER_ID, MEMBER_PASSWARD, MEMBER_NAME, MEMBER_AGE, MEMBER_EMAIL) 
VALUES (101, 'kim', '1234', '김자바', 30, 'kim@gmail.com');
INSERT INTO MY_MEMBER(MEMBER_NUMBER, MEMBER_ID, MEMBER_PASSWARD, MEMBER_NAME, MEMBER_AGE, MEMBER_EMAIL) 
VALUES (102, 'hong', '5678', '홍자바', 25, 'hong@gmail.com');
COMMIT;

#3.
UPDATE MY_MEMBER
SET MEMBER_NAME = '유관순', MEMBER_AGE = MEMBER_AGE + 5
WHERE MEMBER_NUMBER = 101;

#4.
SELECT EMPNO, ENAME, SAL, COMM 
FROM emp
WHERE SAL BETWEEN 500 AND 3000 AND COMM IS NOT NULL;

#5.
SELECT EMPNO, ENAME, HIREDATE
FROM emp
WHERE ENAME LIKE '%기' OR ENAME LIKE '%김%' ORDER BY EMPNO DESC;

#6.
SELECT EMPNO, ENAME, DEPTNO,
 CASE  
 WHEN DEPTNO = 10 THEN '인사부' 
	WHEN DEPTNO = 20 THEN '영업부' 
	WHEN DEPTNO = 30 THEN '개발부' 
	ELSE '생산부'
	END AS '부서명'
FROM emp;


#7.
SELECT EMPNO, ENAME, HIREDATE, IFNULL(COMM,0)
FROM emp
WHERE MONTH(HIREDATE) = 1 
ORDER BY HIREDATE ASC;
#8.

#9.

#10.
SELECT EMPNO, ENAME, HIREDATE, SAL, E.DEPTNO, D.DEPTNO, DNAME
FROM emp E INNER JOIN dept D
ON E.DEPTNO = D.DEPTNO
WHERE DNAME != '인사부' AND SAL >=500
ORDER BY EMPNO DESC, ENAME ASC;












